version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      semver-patch-days: 7
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: gomod
    directory: /sdk
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      semver-patch-days: 7
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: gomod
    directory: /plugins/azurerm
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      semver-patch-days: 7
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
    commit-message:
      prefix: "ci"
      include: "scope"
