// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/tfclassify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceChange represents a resource change from a Terraform plan.
type ResourceChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProviderName    string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Mode            string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Actions         []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Before          []byte                 `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"`                                          // JSON-encoded map
	After           []byte                 `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`                                            // JSON-encoded map
	BeforeSensitive []byte                 `protobuf:"bytes,8,opt,name=before_sensitive,json=beforeSensitive,proto3" json:"before_sensitive,omitempty"` // JSON-encoded sensitive markers
	AfterSensitive  []byte                 `protobuf:"bytes,9,opt,name=after_sensitive,json=afterSensitive,proto3" json:"after_sensitive,omitempty"`    // JSON-encoded sensitive markers
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceChange) Reset() {
	*x = ResourceChange{}
	mi := &file_proto_tfclassify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceChange) ProtoMessage() {}

func (x *ResourceChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceChange.ProtoReflect.Descriptor instead.
func (*ResourceChange) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceChange) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ResourceChange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceChange) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ResourceChange) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ResourceChange) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ResourceChange) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ResourceChange) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *ResourceChange) GetBeforeSensitive() []byte {
	if x != nil {
		return x.BeforeSensitive
	}
	return nil
}

func (x *ResourceChange) GetAfterSensitive() []byte {
	if x != nil {
		return x.AfterSensitive
	}
	return nil
}

// Decision represents a classification decision from an analyzer.
type Decision struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Classification string                 `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Severity       int32                  `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Metadata       []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON-encoded map
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_proto_tfclassify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{1}
}

func (x *Decision) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Decision) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ApplyConfigRequest contains plugin configuration.
type ApplyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"` // Raw HCL bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigRequest) Reset() {
	*x = ApplyConfigRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigRequest) ProtoMessage() {}

func (x *ApplyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyConfigRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

// ApplyConfigResponse is empty on success.
type ApplyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigResponse) Reset() {
	*x = ApplyConfigResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigResponse) ProtoMessage() {}

func (x *ApplyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigResponse.ProtoReflect.Descriptor instead.
func (*ApplyConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{3}
}

// AnalyzeRequest starts the analysis.
type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// broker_id is used by the plugin to dial back to the Runner server.
	BrokerId uint32 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	// classification is the classification name (e.g., "critical") for which analysis is being run.
	// Plugins should emit decisions with this classification.
	Classification string `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	// analyzer_config contains JSON-encoded per-analyzer configuration for this classification.
	AnalyzerConfig []byte `protobuf:"bytes,3,opt,name=analyzer_config,json=analyzerConfig,proto3" json:"analyzer_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *AnalyzeRequest) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *AnalyzeRequest) GetAnalyzerConfig() []byte {
	if x != nil {
		return x.AnalyzerConfig
	}
	return nil
}

// AnalyzeResponse indicates analysis completion.
type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{5}
}

// GetResourceChangesRequest queries for matching resources.
type GetResourceChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patterns      []string               `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceChangesRequest) Reset() {
	*x = GetResourceChangesRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceChangesRequest) ProtoMessage() {}

func (x *GetResourceChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceChangesRequest.ProtoReflect.Descriptor instead.
func (*GetResourceChangesRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{6}
}

func (x *GetResourceChangesRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

// GetResourceChangesResponse contains matching resource changes.
type GetResourceChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ResourceChange      `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceChangesResponse) Reset() {
	*x = GetResourceChangesResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceChangesResponse) ProtoMessage() {}

func (x *GetResourceChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceChangesResponse.ProtoReflect.Descriptor instead.
func (*GetResourceChangesResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{7}
}

func (x *GetResourceChangesResponse) GetChanges() []*ResourceChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

// GetResourceChangeRequest queries for a specific resource.
type GetResourceChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceChangeRequest) Reset() {
	*x = GetResourceChangeRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceChangeRequest) ProtoMessage() {}

func (x *GetResourceChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceChangeRequest.ProtoReflect.Descriptor instead.
func (*GetResourceChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{8}
}

func (x *GetResourceChangeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// GetResourceChangeResponse contains the requested resource change.
type GetResourceChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        *ResourceChange        `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceChangeResponse) Reset() {
	*x = GetResourceChangeResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceChangeResponse) ProtoMessage() {}

func (x *GetResourceChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceChangeResponse.ProtoReflect.Descriptor instead.
func (*GetResourceChangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{9}
}

func (x *GetResourceChangeResponse) GetChange() *ResourceChange {
	if x != nil {
		return x.Change
	}
	return nil
}

// EmitDecisionRequest records a decision for a resource.
type EmitDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalyzerName  string                 `protobuf:"bytes,1,opt,name=analyzer_name,json=analyzerName,proto3" json:"analyzer_name,omitempty"`
	Change        *ResourceChange        `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	Decision      *Decision              `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitDecisionRequest) Reset() {
	*x = EmitDecisionRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitDecisionRequest) ProtoMessage() {}

func (x *EmitDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitDecisionRequest.ProtoReflect.Descriptor instead.
func (*EmitDecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{10}
}

func (x *EmitDecisionRequest) GetAnalyzerName() string {
	if x != nil {
		return x.AnalyzerName
	}
	return ""
}

func (x *EmitDecisionRequest) GetChange() *ResourceChange {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *EmitDecisionRequest) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

// EmitDecisionResponse is empty on success.
type EmitDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitDecisionResponse) Reset() {
	*x = EmitDecisionResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitDecisionResponse) ProtoMessage() {}

func (x *EmitDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitDecisionResponse.ProtoReflect.Descriptor instead.
func (*EmitDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{11}
}

// GetPluginInfoRequest requests plugin metadata.
type GetPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoRequest) Reset() {
	*x = GetPluginInfoRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoRequest) ProtoMessage() {}

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{12}
}

// GetPluginInfoResponse contains plugin metadata for verification.
type GetPluginInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the plugin name (e.g., "terraform", "azurerm").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version is the plugin version (e.g., "0.1.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// sdk_version is the SDK version the plugin was built with (e.g., "0.1.0").
	SdkVersion string `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// host_version_constraint specifies which host versions the plugin supports.
	// Uses semver constraint syntax (e.g., ">= 0.1.0").
	HostVersionConstraint string `protobuf:"bytes,4,opt,name=host_version_constraint,json=hostVersionConstraint,proto3" json:"host_version_constraint,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{13}
}

func (x *GetPluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPluginInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetPluginInfoResponse) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *GetPluginInfoResponse) GetHostVersionConstraint() string {
	if x != nil {
		return x.HostVersionConstraint
	}
	return ""
}

// GetConfigSchemaRequest requests the plugin's configuration schema.
type GetConfigSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaRequest) Reset() {
	*x = GetConfigSchemaRequest{}
	mi := &file_proto_tfclassify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaRequest) ProtoMessage() {}

func (x *GetConfigSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaRequest) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{14}
}

// GetConfigSchemaResponse contains the configuration schema for validation.
type GetConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*ConfigAttribute     `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchemaResponse) Reset() {
	*x = GetConfigSchemaResponse{}
	mi := &file_proto_tfclassify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchemaResponse) ProtoMessage() {}

func (x *GetConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigSchemaResponse) GetAttributes() []*ConfigAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ConfigAttribute describes a single configuration attribute.
type ConfigAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAttribute) Reset() {
	*x = ConfigAttribute{}
	mi := &file_proto_tfclassify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAttribute) ProtoMessage() {}

func (x *ConfigAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tfclassify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAttribute.ProtoReflect.Descriptor instead.
func (*ConfigAttribute) Descriptor() ([]byte, []int) {
	return file_proto_tfclassify_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigAttribute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigAttribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_tfclassify_proto protoreflect.FileDescriptor

const file_proto_tfclassify_proto_rawDesc = "" +
	"\n" +
	"\x16proto/tfclassify.proto\x12\n" +
	"tfclassify\"\x93\x02\n" +
	"\x0eResourceChange\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\x12\x16\n" +
	"\x06before\x18\x06 \x01(\fR\x06before\x12\x14\n" +
	"\x05after\x18\a \x01(\fR\x05after\x12)\n" +
	"\x10before_sensitive\x18\b \x01(\fR\x0fbeforeSensitive\x12'\n" +
	"\x0fafter_sensitive\x18\t \x01(\fR\x0eafterSensitive\"\x82\x01\n" +
	"\bDecision\x12&\n" +
	"\x0eclassification\x18\x01 \x01(\tR\x0eclassification\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\x05R\bseverity\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\",\n" +
	"\x12ApplyConfigRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x15\n" +
	"\x13ApplyConfigResponse\"~\n" +
	"\x0eAnalyzeRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12&\n" +
	"\x0eclassification\x18\x02 \x01(\tR\x0eclassification\x12'\n" +
	"\x0fanalyzer_config\x18\x03 \x01(\fR\x0eanalyzerConfig\"\x11\n" +
	"\x0fAnalyzeResponse\"7\n" +
	"\x19GetResourceChangesRequest\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\"R\n" +
	"\x1aGetResourceChangesResponse\x124\n" +
	"\achanges\x18\x01 \x03(\v2\x1a.tfclassify.ResourceChangeR\achanges\"4\n" +
	"\x18GetResourceChangeRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"O\n" +
	"\x19GetResourceChangeResponse\x122\n" +
	"\x06change\x18\x01 \x01(\v2\x1a.tfclassify.ResourceChangeR\x06change\"\xa0\x01\n" +
	"\x13EmitDecisionRequest\x12#\n" +
	"\ranalyzer_name\x18\x01 \x01(\tR\fanalyzerName\x122\n" +
	"\x06change\x18\x02 \x01(\v2\x1a.tfclassify.ResourceChangeR\x06change\x120\n" +
	"\bdecision\x18\x03 \x01(\v2\x14.tfclassify.DecisionR\bdecision\"\x16\n" +
	"\x14EmitDecisionResponse\"\x16\n" +
	"\x14GetPluginInfoRequest\"\x9e\x01\n" +
	"\x15GetPluginInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x126\n" +
	"\x17host_version_constraint\x18\x04 \x01(\tR\x15hostVersionConstraint\"\x18\n" +
	"\x16GetConfigSchemaRequest\"V\n" +
	"\x17GetConfigSchemaResponse\x12;\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1b.tfclassify.ConfigAttributeR\n" +
	"attributes\"w\n" +
	"\x0fConfigAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription2\xd5\x02\n" +
	"\rPluginService\x12T\n" +
	"\rGetPluginInfo\x12 .tfclassify.GetPluginInfoRequest\x1a!.tfclassify.GetPluginInfoResponse\x12Z\n" +
	"\x0fGetConfigSchema\x12\".tfclassify.GetConfigSchemaRequest\x1a#.tfclassify.GetConfigSchemaResponse\x12N\n" +
	"\vApplyConfig\x12\x1e.tfclassify.ApplyConfigRequest\x1a\x1f.tfclassify.ApplyConfigResponse\x12B\n" +
	"\aAnalyze\x12\x1a.tfclassify.AnalyzeRequest\x1a\x1b.tfclassify.AnalyzeResponse2\xa9\x02\n" +
	"\rRunnerService\x12c\n" +
	"\x12GetResourceChanges\x12%.tfclassify.GetResourceChangesRequest\x1a&.tfclassify.GetResourceChangesResponse\x12`\n" +
	"\x11GetResourceChange\x12$.tfclassify.GetResourceChangeRequest\x1a%.tfclassify.GetResourceChangeResponse\x12Q\n" +
	"\fEmitDecision\x12\x1f.tfclassify.EmitDecisionRequest\x1a .tfclassify.EmitDecisionResponseB%Z#github.com/jokarl/tfclassify/sdk/pbb\x06proto3"

var (
	file_proto_tfclassify_proto_rawDescOnce sync.Once
	file_proto_tfclassify_proto_rawDescData []byte
)

func file_proto_tfclassify_proto_rawDescGZIP() []byte {
	file_proto_tfclassify_proto_rawDescOnce.Do(func() {
		file_proto_tfclassify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tfclassify_proto_rawDesc), len(file_proto_tfclassify_proto_rawDesc)))
	})
	return file_proto_tfclassify_proto_rawDescData
}

var file_proto_tfclassify_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_tfclassify_proto_goTypes = []any{
	(*ResourceChange)(nil),             // 0: tfclassify.ResourceChange
	(*Decision)(nil),                   // 1: tfclassify.Decision
	(*ApplyConfigRequest)(nil),         // 2: tfclassify.ApplyConfigRequest
	(*ApplyConfigResponse)(nil),        // 3: tfclassify.ApplyConfigResponse
	(*AnalyzeRequest)(nil),             // 4: tfclassify.AnalyzeRequest
	(*AnalyzeResponse)(nil),            // 5: tfclassify.AnalyzeResponse
	(*GetResourceChangesRequest)(nil),  // 6: tfclassify.GetResourceChangesRequest
	(*GetResourceChangesResponse)(nil), // 7: tfclassify.GetResourceChangesResponse
	(*GetResourceChangeRequest)(nil),   // 8: tfclassify.GetResourceChangeRequest
	(*GetResourceChangeResponse)(nil),  // 9: tfclassify.GetResourceChangeResponse
	(*EmitDecisionRequest)(nil),        // 10: tfclassify.EmitDecisionRequest
	(*EmitDecisionResponse)(nil),       // 11: tfclassify.EmitDecisionResponse
	(*GetPluginInfoRequest)(nil),       // 12: tfclassify.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil),      // 13: tfclassify.GetPluginInfoResponse
	(*GetConfigSchemaRequest)(nil),     // 14: tfclassify.GetConfigSchemaRequest
	(*GetConfigSchemaResponse)(nil),    // 15: tfclassify.GetConfigSchemaResponse
	(*ConfigAttribute)(nil),            // 16: tfclassify.ConfigAttribute
}
var file_proto_tfclassify_proto_depIdxs = []int32{
	0,  // 0: tfclassify.GetResourceChangesResponse.changes:type_name -> tfclassify.ResourceChange
	0,  // 1: tfclassify.GetResourceChangeResponse.change:type_name -> tfclassify.ResourceChange
	0,  // 2: tfclassify.EmitDecisionRequest.change:type_name -> tfclassify.ResourceChange
	1,  // 3: tfclassify.EmitDecisionRequest.decision:type_name -> tfclassify.Decision
	16, // 4: tfclassify.GetConfigSchemaResponse.attributes:type_name -> tfclassify.ConfigAttribute
	12, // 5: tfclassify.PluginService.GetPluginInfo:input_type -> tfclassify.GetPluginInfoRequest
	14, // 6: tfclassify.PluginService.GetConfigSchema:input_type -> tfclassify.GetConfigSchemaRequest
	2,  // 7: tfclassify.PluginService.ApplyConfig:input_type -> tfclassify.ApplyConfigRequest
	4,  // 8: tfclassify.PluginService.Analyze:input_type -> tfclassify.AnalyzeRequest
	6,  // 9: tfclassify.RunnerService.GetResourceChanges:input_type -> tfclassify.GetResourceChangesRequest
	8,  // 10: tfclassify.RunnerService.GetResourceChange:input_type -> tfclassify.GetResourceChangeRequest
	10, // 11: tfclassify.RunnerService.EmitDecision:input_type -> tfclassify.EmitDecisionRequest
	13, // 12: tfclassify.PluginService.GetPluginInfo:output_type -> tfclassify.GetPluginInfoResponse
	15, // 13: tfclassify.PluginService.GetConfigSchema:output_type -> tfclassify.GetConfigSchemaResponse
	3,  // 14: tfclassify.PluginService.ApplyConfig:output_type -> tfclassify.ApplyConfigResponse
	5,  // 15: tfclassify.PluginService.Analyze:output_type -> tfclassify.AnalyzeResponse
	7,  // 16: tfclassify.RunnerService.GetResourceChanges:output_type -> tfclassify.GetResourceChangesResponse
	9,  // 17: tfclassify.RunnerService.GetResourceChange:output_type -> tfclassify.GetResourceChangeResponse
	11, // 18: tfclassify.RunnerService.EmitDecision:output_type -> tfclassify.EmitDecisionResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_tfclassify_proto_init() }
func file_proto_tfclassify_proto_init() {
	if File_proto_tfclassify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tfclassify_proto_rawDesc), len(file_proto_tfclassify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_tfclassify_proto_goTypes,
		DependencyIndexes: file_proto_tfclassify_proto_depIdxs,
		MessageInfos:      file_proto_tfclassify_proto_msgTypes,
	}.Build()
	File_proto_tfclassify_proto = out.File
	file_proto_tfclassify_proto_goTypes = nil
	file_proto_tfclassify_proto_depIdxs = nil
}
