package scaffold

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/jokarl/tfclassify/internal/config"
)

var templateFuncs = template.FuncMap{
	"patterns": formatPatterns,
	"types":    formatTypes,
}

// Generate renders a .tfclassify.hcl configuration file from the
// categorization result. The output is validated through config.Parse
// to guarantee syntactic correctness.
func Generate(result *CategorizeResult) ([]byte, error) {
	tmpl, err := template.New("config").Funcs(templateFuncs).Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing template: %w", err)
	}

	data := templateData{
		TotalTypes:    countTypes(result),
		Critical:      result.Critical,
		Standard:      result.Standard,
		Uncategorized: result.Uncategorized,
		Modules:       result.Modules,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	out := buf.Bytes()

	// Validate the generated config parses correctly
	if _, err := config.Parse(out, "scaffold-output.hcl"); err != nil {
		return nil, fmt.Errorf("generated config is invalid (this is a bug): %w", err)
	}

	return out, nil
}

type templateData struct {
	TotalTypes    int
	Critical      []Category
	Standard      []Category
	Uncategorized []string
	Modules       []string
}

func countTypes(r *CategorizeResult) int {
	n := len(r.Uncategorized)
	for _, c := range r.Critical {
		n += len(c.Types)
	}
	for _, c := range r.Standard {
		n += len(c.Types)
	}
	return n
}

// formatPatterns renders a list of patterns as an HCL list literal.
func formatPatterns(patterns []string) string {
	quoted := make([]string, len(patterns))
	for i, p := range patterns {
		quoted[i] = `"` + p + `"`
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// formatTypes renders resource types as an HCL comment list.
func formatTypes(types []string) string {
	return strings.Join(types, ", ")
}

var configTemplate = `# tfclassify configuration
#
# Generated by: tfclassify scaffold
# Resource types: {{ .TotalTypes }}
#
# This is a starter configuration. Review and adjust the rules below to match
# your organization's change approval requirements.
#
# Tips:
#   - Add "actions = [\"delete\"]" to restrict rules to specific change types
#   - Use blast_radius {} blocks to flag large-scale changes
#   - Use topology {} blocks to flag changes with many downstream dependents
#   - Run "tfclassify validate" to check this file for errors
{{- if gt (len .Modules) 0 }}
#
# Modules detected in your state:
{{- range .Modules }}
#   {{ . }}
{{- end }}
#
# You can scope rules to specific modules with:
#   rule {
#     module   = ["module.production"]
#     resource = ["*"]
#     actions  = ["delete"]
#   }
{{- end }}

# ── Critical ─────────────────────────────────────────────────────────────────
#
# Changes that require elevated approval. Review these rules carefully and
# adjust the resource patterns and actions to match your approval workflow.
{{ if gt (len .Critical) 0 -}}
classification "critical" {
  description = "Requires elevated approval"
{{ range .Critical }}
  # {{ .Name }}: {{ .Description }}
  # Matched: {{ types .Types }}
  rule {
    description = "{{ .Name }} changes require elevated approval"
    resource    = {{ patterns .Patterns }}
  }
{{ end -}}
}
{{ else -}}
# No critical resource types detected. Add classification rules as needed:
#
# classification "critical" {
#   description = "Requires elevated approval"
#   rule {
#     resource = ["*_role_*", "*_iam_*"]
#     actions  = ["delete"]
#   }
# }
{{ end }}
# ── Standard ─────────────────────────────────────────────────────────────────
#
# Standard change process. The catch-all rule ensures every resource gets
# classified. Resources matched by higher-precedence rules above won't
# reach this level.

classification "standard" {
  description = "Standard change process"

  rule {
    description = "All infrastructure changes not covered above"
    resource    = ["*"]
  }
}

# ── Auto ─────────────────────────────────────────────────────────────────────

classification "auto" {
  description = "No approval needed"

  rule {
    description = "No actual changes detected"
    resource    = ["*"]
    actions     = ["no-op"]
  }
}

# ── Precedence ───────────────────────────────────────────────────────────────
#
# Ordered list of classification names, highest priority first.
# Rules are evaluated in this order — first match wins per resource.
# Exit codes are derived from position (critical=2, standard=1, auto=0).

precedence = [{{ if gt (len .Critical) 0 }}"critical", {{ end }}"standard", "auto"]

# ── Defaults ─────────────────────────────────────────────────────────────────

defaults {
  # Classification for resources that match no rule.
  unclassified = "standard"

  # Classification when the plan contains zero changes.
  no_changes = "auto"

  # Uncomment to classify drift corrections separately:
  # drift_classification = "standard"

  # Uncomment to ignore cosmetic attribute changes:
  # ignore_attributes = ["tags", "tags_all"]

  # Scoped ignore rules (CR-0035) — apply only when resource/module globs match.
  # Useful when an attribute should be ignored for one provider but not others,
  # e.g. azapi_resource.output (a computed read-back, not a user change):
  # ignore_attribute "azapi_output" {
  #   description = "azapi computed refresh"
  #   resource    = ["azapi_resource"]
  #   attributes  = ["output"]
  # }
}
`
