package scaffold

import (
	"strings"
	"testing"

	"github.com/jokarl/tfclassify/internal/config"
)

func TestGenerate_ValidHCL(t *testing.T) {
	result := &CategorizeResult{
		Critical: []Category{
			{
				Name:        "IAM",
				Description: "Identity and access management",
				Types:       []string{"azurerm_role_assignment", "azurerm_role_definition"},
				Patterns:    []string{"*_role_assignment", "*_role_definition"},
			},
		},
		Standard: []Category{
			{
				Name:        "Networking",
				Description: "Network infrastructure",
				Types:       []string{"azurerm_virtual_network", "azurerm_subnet"},
				Patterns:    []string{"*_virtual_network", "*_subnet"},
			},
		},
		Uncategorized: []string{"azurerm_resource_group"},
	}

	out, err := Generate(result)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Verify it parses as valid config
	cfg, err := config.Parse(out, "test.hcl")
	if err != nil {
		t.Fatalf("generated config failed to parse: %v", err)
	}

	// Check precedence includes critical
	if len(cfg.Precedence) != 3 {
		t.Errorf("expected 3 precedence entries, got %d: %v", len(cfg.Precedence), cfg.Precedence)
	}
	if cfg.Precedence[0] != "critical" {
		t.Errorf("first precedence should be critical, got %q", cfg.Precedence[0])
	}
}

func TestGenerate_NoCritical(t *testing.T) {
	result := &CategorizeResult{
		Uncategorized: []string{"random_password", "null_resource"},
	}

	out, err := Generate(result)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Should parse successfully
	cfg, err := config.Parse(out, "test.hcl")
	if err != nil {
		t.Fatalf("generated config failed to parse: %v", err)
	}

	// Precedence should not include critical
	for _, p := range cfg.Precedence {
		if p == "critical" {
			t.Error("precedence should not include critical when no critical categories")
		}
	}

	// Should have commented-out critical example
	s := string(out)
	if !strings.Contains(s, "# No critical resource types detected") {
		t.Error("expected commented-out critical example")
	}
}

func TestGenerate_WithModules(t *testing.T) {
	result := &CategorizeResult{
		Critical: []Category{
			{
				Name:        "IAM",
				Description: "IAM changes",
				Types:       []string{"azurerm_role_assignment"},
				Patterns:    []string{"*_role_assignment"},
			},
		},
		Modules: []string{"module.network", "module.production"},
	}

	out, err := Generate(result)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	s := string(out)
	if !strings.Contains(s, "module.network") {
		t.Error("expected module.network in output")
	}
	if !strings.Contains(s, "module.production") {
		t.Error("expected module.production in output")
	}
	if !strings.Contains(s, "module   =") {
		t.Error("expected module scoping hint in output")
	}
}

func TestGenerate_ContainsComments(t *testing.T) {
	result := &CategorizeResult{
		Critical: []Category{
			{
				Name:        "IAM",
				Description: "IAM changes",
				Types:       []string{"azurerm_role_assignment"},
				Patterns:    []string{"*_role_assignment"},
			},
		},
	}

	out, err := Generate(result)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	s := string(out)
	checks := []string{
		"Generated by: tfclassify scaffold",
		"# ── Critical",
		"# ── Standard",
		"# ── Precedence",
		"# ── Defaults",
		"tfclassify validate",
		"blast_radius",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("expected output to contain %q", check)
		}
	}
}

func TestGenerate_ResourceTypeCount(t *testing.T) {
	result := &CategorizeResult{
		Critical: []Category{
			{
				Name:     "IAM",
				Types:    []string{"azurerm_role_assignment"},
				Patterns: []string{"*_role_assignment"},
			},
		},
		Uncategorized: []string{"azurerm_resource_group", "azurerm_storage_account"},
	}

	out, err := Generate(result)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	if !strings.Contains(string(out), "Resource types: 3") {
		t.Error("expected resource type count of 3")
	}
}
